### ISSUE TITLE
Clean up animal list

### ISSUE THREAD

**Issue by karlbright** [karlbright/metal-gear-solid-v-name-generator#1]
Currently the animal list has a lot of dog breeds and other interesting animals included that I have never heard of. 

An alternative is the [common animals list from Corpora](https://github.com/dariusk/corpora/blob/master/data/animals/common.json) but this doesn't include Tree Frog. This could be added of course.

I'd love to see an official list of animals from MGSV itself but I was not able to find one.

**Comment by hellstad** [comment]
[MGSV animals](http://metalgear.wikia.com/wiki/Codename_(gameplay)#Metal_Gear_Solid_V:_The_Phantom_Pain)

**Comment by karlbright** [comment]
That looks to be the codename you get when you finish a mission.
